language: node_js
node_js:
 - "node"
before_install:
 - npm install -g yarn
 - psql -c 'create database internal_active_user_test;' -U postgres
install:
 - yarn
after_script:
 - npm run coveralls
cache:
  yarn: true
  directories:
    - node_modules
services:
  - postgresql
